name: fGolem
version: '${project.version}'
main: org.fejzu.golem.Plugin
api-version: '1.16'

author: fejzu
website: www.fejzu.pl

commands:
  collections:
  collection:
    aliases:
      - zbiorka
      - zrzutka
